SELECT * FROM hr.employees; -- SALARY, JOB_ID
SELECT * FROM hr.jobs; -- MAX_SALARY, JOB_ID

SELECT 
    E.SALARY AS Cargo,
    (CASE
        WHEN J.MAX_SALARY BETWEEN 5000 AND 10000 THEN 'Baixo'
        WHEN J.MAX_SALARY BETWEEN 10001 AND 20000 THEN 'Médio'
        WHEN J.MAX_SALARY BETWEEN 20001 AND 30000 THEN 'Alto'
        WHEN J.MAX_SALARY > 30000 THEN 'Altíssimo'
    END) AS Nível
FROM
    hr.employees AS E
        INNER JOIN
    hr.jobs AS J
WHERE
    J.JOB_ID = E.JOB_ID
    ORDER BY J.JOB_ID;