USE hr;
SELECT JOB_TITLE AS CARGO, CASE
WHEN MAX_SALARY <= 10000 THEN 'BAIXO'
WHEN MAX_SALARY BETWEEN 10001 AND 20000 THEN 'Médio'
WHEN MAX_SALARY BETWEEN 20001 AND 30000 THEN 'Alto'
ELSE 'ALTISSIMO'
END AS 'NIVEL'
-- from jobs
-- ORDER BY JOB_TITLE;