SELECT UCASE(
  CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)
) AS 'Nome completo',
H.START_DATE AS 'Data de início',
SALARY AS Salário
FROM hr.employees AS E
RIGHT JOIN hr.job_history AS H
ON H.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE MONTH(H.START_DATE) BETWEEN 01 AND 03
ORDER BY CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME),
H.START_DATE;
