SELECT 
    t2.JOB_TITLE AS 'Cargo',
    (CASE
        WHEN MAX(t1.SALARY) BETWEEN 5000 AND 10000 THEN 'Baixo'
        WHEN MAX(t1.SALARY) BETWEEN 10001 AND 20000 THEN 'Médio'
        WHEN MAX(t1.SALARY) BETWEEN 20001 AND 30000 THEN 'Alto'
        WHEN MAX(t1.SALARY) > 30000 THEN 'Altíssimo'
        ELSE 'Baixo'
    END) AS 'Nível'
FROM
    hr.employees AS t1
        INNER JOIN
    hr.jobs AS t2 ON t1.JOB_ID = t2.JOB_ID
GROUP BY t1.JOB_ID
ORDER BY t2.JOB_TITLE;
