USE hr;

DELIMITER $$

CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario(EMPLOYEE_EMAIL VARCHAR(100))
RETURNS INT READS SQL DATA
BEGIN
		DECLARE EMPLOYEE_TOTAL_JOBS INT;
		SELECT COUNT(*)
    FROM job_history
    WHERE EMPLOYEE_ID = (SELECT EMPLOYEE_ID FROM employees WHERE EMAIL = EMPLOYEE_EMAIL)
    INTO EMPLOYEE_TOTAL_JOBS;
    RETURN EMPLOYEE_TOTAL_JOBS;
END $$

DELIMITER ;