USE hr;
SELECT 
    JOB_TITLE AS 'CARGO',
    MAX_SALARY - MIN_SALARY AS 'VARIAÇAO SALARIAL',
    ROUND(MIN_SALARY / 12, 2) AS 'MEDIA MINIMA MENSAL',
    ROUND(MAX_SALARY / 12, 2) AS 'MEDIA MAXIMA MENSAL'
FROM
    jobs
ORDER BY `VARIAÇAO SALARIAL` , `CARGO`;
    