SELECT J.JOB_TITLE AS Cargo,
ROUND(AVG(E.SALARY), 2) AS 'Média salarial',
CASE
  WHEN AVG(E.SALARY) < 5800 THEN 'Júnior'
  WHEN AVG(E.SALARY) < 7500 THEN 'Pleno'
  WHEN AVG(E.SALARY) < 10500 THEN 'Sênior'
ELSE 'CEO'
END AS Senioridade
FROM hr.employees AS E
INNER JOIN hr.jobs AS J
ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_ID
ORDER BY AVG(ROUND(E.SALARY, 2)),
J.JOB_TITLE;
