use hr;
SELECT 
    *
FROM
    employees;
SELECT 
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS 'NOME FUNCIONARIO 1',
    e.SALARY AS 'SALARIO FUNCIONARIO 1',
    e.PHONE_NUMBER AS 'TELEFONE FUNCIONARIO 1',
    CONCAT(f.FIRST_NAME, ' ', f.LAST_NAME) AS 'NOME FUNCIONARIO 2',
    f.SALARY AS 'SALARIO FUNCIONARIO 2',
    f.PHONE_NUMBER AS 'TELEFONE FUNCIONARIO 2'
FROM
    employees e,
    employees f
WHERE
    e.JOB_ID = f.JOB_ID
        AND CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) <> CONCAT(f.FIRST_NAME, ' ', f.LAST_NAME)
ORDER BY `NOME FUNCIONARIO 1` , `NOME FUNCIONARIO 2`;