USE hr;
SELECT 
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS 'NOME COMPLETO',
    jh.START_DATE AS 'DATA DE INICIO DO CARGO',
    e.SALARY AS 'SALARIO'
FROM
    employees e
    inner join job_history jh on e.EMPLOYEE_ID = jh.EMPLOYEE_ID AND MONTH(jh.START_DATE) IN (01, 02, 03)
    ORDER BY `NOME COMPLETO`, `DATA DE INICIO DO CARGO`;