SELECT
JB.JOB_TITLE AS Cargo,
ROUND(AVG(EMP.SALARY), 2) AS 'Média salarial',
CASE
 WHEN ROUND(AVG(EMP.SALARY), 2) BETWEEN 2000 AND 5800 THEN 'Júnior'
 WHEN ROUND(AVG(EMP.SALARY), 2) BETWEEN 5801 AND 7500 THEN 'Pleno'
 WHEN ROUND(AVG(EMP.SALARY), 2) BETWEEN 7501 AND 10500 THEN 'Sênior'
 WHEN ROUND(AVG(EMP.SALARY), 2) > 10500 THEN 'CEO'
END AS Senioridade
FROM hr.employees AS EMP
INNER JOIN hr.jobs AS JB
WHERE EMP.JOB_ID = JB.JOB_ID
GROUP BY EMP.JOB_ID
ORDER BY ROUND(AVG(EMP.SALARY), 2) ASC, Cargo ASC;